# fly.toml app configuration file generated for gerardo-wordpress-test on 2023-06-26T20:37:08-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gerardo-wordpress-test"
primary_region = "dfw"

[env]
  WORDPRESS_CONFIG_EXTRA = "define(\"MYSQL_CLIENT_FLAGS\", MYSQLI_CLIENT_SSL);"

[[services]]
  protocol = "tcp"
  internal_port = 80

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [services.concurrency]
    hard_limit = 50
    soft_limit = 25

  [[services.tcp_checks]]
    interval = "5s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0
